kubeconfig update 13th April 2025

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -11,16 +11,14 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
-     
     - name: Set up kubeconfig
       run: |
-          mkdir -p $HOME/.kube
-          echo "${{ secrets.KUBECONFIG_SECRET }}" > $HOME/.kube/config
-          export KUBECONFIG=$HOME/.kube/config
-          # Verify the configuration:
-          kubectl config view
-          kubectl cluster-info
-
+        
+        echo "${{ secrets.KUBECONFIG_SECRET }}" > kubeconfig
+        export KUBECONFIG=$PWD/kubeconfig
+        kubectl config view || echo "Failed to view kubeconfig"
+    
+      
     - name: Verify kubectl installation
       run: |
         # Check if kubectl is available
